# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{crackoid}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["sdomino"]
  s.date = %q{2011-07-05}
  s.email = %q{sdomino@pagodabox.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "History",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "crackoid.gemspec",
     "lib/crackoid.rb",
     "lib/crackoid/core_extensions.rb",
     "lib/crackoid/json.rb",
     "lib/crackoid/xml.rb",
     "test/crack_test.rb",
     "test/data/twittersearch-firefox.json",
     "test/data/twittersearch-ie.json",
     "test/hash_test.rb",
     "test/json_test.rb",
     "test/string_test.rb",
     "test/test_helper.rb",
     "test/xml_test.rb"
  ]
  s.homepage = %q{http://github.com/sdomino/crack}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{crackoid}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{This gem is jnunemaker's 'Crack', with a fix so that XML parsing now works with mongoid!}
  s.test_files = [
    "test/crack_test.rb",
     "test/hash_test.rb",
     "test/json_test.rb",
     "test/string_test.rb",
     "test/test_helper.rb",
     "test/xml_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

